name: razorpay_dart
description: A Dart package for interacting with the Razorpay API.
version: 0.0.3
repository: https://github.com/devalfaz/razorpay_dart
homepage: https://github.com/devalfaz/razorpay_dart
issues: https://github.com/devalfaz/razorpay_dart/issues

topics:
  - razorpay
  - payment
  - gateway
  - finance

environment:
  sdk: ^3.8.0

dependencies:
  crypto: ^3.0.7
  dio: ^5.9.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  pointycastle: ^4.0.0

dev_dependencies:
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.9.5
  lints: ^6.0.0
